version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.17.1
    container_name: "elasticsearch2"
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "ES_JAVA_OPTS=-Xms64m -Xmx128m"
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    volumes:
      - ./elasticsearch/config:/usr/share/elasticsearch/config

  kibana:
    image: kibana:7.17.1
    container_name: kibana2
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    volumes:
      - ./kibana/config:/usr/share/kibana/config
      # - ./kibana/data:/usr/share/kibana/data


